version: "3.4"

services:
  portal:
    image: martialbe/one-api:latest
    container_name: one-hub-portal
    restart: always
    command: --log-dir /app/logs
    ports:
      - "${ONE_HUB_PORT}:3000"
    volumes:
      - ./data/portal:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(db:3306)/${MYSQL_DATABASE} # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string # 修改为随机字符串
      - TZ=Asia/Shanghai
    #      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
    #      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
    #      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    depends_on:
      - redis
      - db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost:${ONE_HUB_PORT}/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: one-hub-redis
    restart: always

  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    container_name: one-hub-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql # 挂载目录，持久化存储
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      TZ: Asia/Shanghai # 设置时区
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" # 设置 root 用户的密码
      MYSQL_USER: "${MYSQL_USER}" # 创建专用用户
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"  # 设置专用用户密码
      MYSQL_DATABASE: "${MYSQL_DATABASE}" # 自动创建数据库
